### ISSUE TITLE
Crashes when I try to share screen

### ISSUE THREAD

**Issue by IvanLotoff** [OddCN/screen-share-to-browser#6]
java.lang.RuntimeException: Stub!
        at org.apache.http.params.AbstractHttpParams.<init>(AbstractHttpParams.java:6)
        at org.apache.http.params.BasicHttpParams.<init>(BasicHttpParams.java:7)
        at com.yanzhenjie.andserver.CoreThread.createHttpParams(CoreThread.java:109)
        at com.yanzhenjie.andserver.CoreThread.run(CoreThread.java:175)

**Comment by IvanLotoff** [comment]
I migrated to androidX

**Comment by VishV-Android** [comment]
getting same error
